version: "3"

networks:
  techers-task:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nfq-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - techers-task

  php:
    image: php:7.4-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfq-php74
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - techers-task

  mysql:
    image: mysql:5.7
    container_name: nfq-mysql57
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - techers-task
