version: "3"

networks:
  mysql57:

services:

  mysql:
    image: mysql:5.7
    container_name: nfq-mysql57
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - mysql57
